from __future__ import annotations

import os
from pathlib import Path
from typing import List, Tuple

from pyproj import CRS

from .grid import ShorelinesDomain
from .initial_conditions import ShorelinesInitialConditions
from .input import ShorelinesInput
from .nourishments import ShorelinesNourishments
from .output import ShorelinesOutput
from .structures import ShorelinesStructures
from .wave_boundary_conditions import ShorelinesWaveBoundaryConditions


class Shorelines:
    def __init__(self, root=None, crs=3395, mode="w", runfile=None):
        if not root:
            root = os.getcwd()

        self.function_path = r"D:\oss\shorelinestki\trunk\functions"
        self.path = str(Path(root))
        self.input = ShorelinesInput(self.path, runfile=runfile)
        # if crs is an integer, assume it is an EPSG code
        if isinstance(crs, int):
            crs = CRS.from_epsg(crs)
        self.crs = crs
        self.grid = ShorelinesDomain(self)
        self.initial_conditions = ShorelinesInitialConditions(self)
        self.wave_boundary_conditions = ShorelinesWaveBoundaryConditions(self)
        self.structures = ShorelinesStructures(self)
        self.nourishments = ShorelinesNourishments(self)
        self.output = ShorelinesOutput()

        if mode == "r":
            self.input.read()
            if getattr(self.input.variables, "epsg", None) is not None:
                self.crs = CRS.from_epsg(self.input.variables.epsg)
            self.read_attribute_files()

    def read(self):
        """Read the runfile and supported attribute files."""
        self.input.read()
        if getattr(self.input.variables, "epsg", None) is not None:
            self.crs = CRS.from_epsg(self.input.variables.epsg)
        self.read_attribute_files()

    def write(self):
        """Write ShorelineS runfile and generated attribute files."""
        Path(self.path).mkdir(parents=True, exist_ok=True)
        self.write_attribute_files()
        self.input.write()

    def read_attribute_files(self):
        self.grid.read()

        self.initial_conditions.read()

        self.wave_boundary_conditions.read()

        self.structures.read()

    def write_attribute_files(self):
        """Writes all attribute files"""
        self.grid.write()

        self.wave_boundary_conditions.write()
        self.structures.write()
        self.initial_conditions.write()
        self.nourishments.write()

    def clear_spatial_attributes(self):
        """Clear spatial data that can be regenerated by the toolbox."""
        self.grid = ShorelinesDomain(self)
        self.wave_boundary_conditions = ShorelinesWaveBoundaryConditions(self)
        self.structures = ShorelinesStructures(self)
        self.initial_conditions = ShorelinesInitialConditions(self)
        self.nourishments = ShorelinesNourishments(self)

    def write_matlab_runner(self, name=None, shoreline_functions_path=None) -> Path:
        """Write a MATLAB script that starts the generated ShorelineS case."""
        if shoreline_functions_path is None:
            shoreline_functions_path = self.function_path
        if name is None:
            name = f"run_{Path(self.input.runfile_name).stem}.m"
        path = Path(self.path) / name
        runfile = self.input.runfile_name.replace("\\", "/")
        functions_path = str(shoreline_functions_path).replace("'", "''")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "\n".join(
                [
                    f"addpath(genpath('{functions_path}'));",
                    f"runShorelineS('{runfile}');",
                    "",
                ]
            ),
            encoding="utf-8",
            newline="\n",
        )
        return path

    def check_times(self) -> Tuple[bool, List[str]]:
        # Check that the boundary and other forcing fully covers the simulation time
        messages = []
        okay = True

        # Boundary conditions
        ok, message = self.wave_boundary_conditions.check_times()
        if not ok:
            okay = False
            messages.append(message)

        return okay, messages
