from __future__ import annotations

import os
from pathlib import Path
from typing import Literal

from pyproj import CRS

from .climate_change import ShorelinesClimateChange
from .dunes import ShorelinesDunes
from .grid import ShorelinesDomain
from .initial_conditions import ShorelinesInitialConditions
from .input import ShorelinesInput
from .io import PathLike, normalize_optional_file_name
from .nourishments import ShorelinesNourishments
from .output import ShorelinesOutput
from .runup import ShorelinesRunup
from .structures import ShorelinesStructures
from .tide import ShorelinesTide
from .wave_boundary_conditions import ShorelinesWaveBoundaryConditions


class Shorelines:
    def __init__(
        self,
        root: PathLike | None = None,
        crs: int | str | CRS = 3395,
        mode: Literal["r", "w"] = "w",
        runfile: PathLike | None = None,
    ) -> None:
        if not root:
            root = os.getcwd()
        if mode not in {"r", "w"}:
            raise ValueError("mode must be 'r' or 'w'")

        self.function_path = r"D:\oss\shorelinestki\trunk\functions"
        self.path = str(Path(root))
        self.input = ShorelinesInput(
            self.path, runfile=normalize_optional_file_name(runfile, argument="runfile")
        )
        self.crs = CRS.from_user_input(crs)
        self.grid = ShorelinesDomain(self)
        self.initial_conditions = ShorelinesInitialConditions(self)
        self.dunes = ShorelinesDunes(self)
        self.wave_boundary_conditions = ShorelinesWaveBoundaryConditions(self)
        self.structures = ShorelinesStructures(self)
        self.nourishments = ShorelinesNourishments(self)
        self.tide = ShorelinesTide(self)
        self.runup = ShorelinesRunup(self)
        self.climate_change = ShorelinesClimateChange(self)
        self.output = ShorelinesOutput()

        if mode == "r":
            self.input.read()
            if getattr(self.input.variables, "epsg", None) is not None:
                self.crs = CRS.from_epsg(self.input.variables.epsg)
            self.read_attribute_files()

    def read(self) -> None:
        """Read the runfile and supported attribute files."""
        self.input.read()
        if getattr(self.input.variables, "epsg", None) is not None:
            self.crs = CRS.from_epsg(self.input.variables.epsg)
        self.read_attribute_files()

    def write(self) -> None:
        """Write ShorelineS runfile and generated attribute files."""
        Path(self.path).mkdir(parents=True, exist_ok=True)
        self.write_attribute_files()
        self.input.write()

    def read_attribute_files(self) -> None:
        """
        Read all supported attribute files referenced by the runfile.
        """
        self.grid.read()

        self.initial_conditions.read()
        self.dunes.read()

        self.wave_boundary_conditions.read()

        self.structures.read()

        self.nourishments.read()

        self.tide.read()

        self.runup.read()

        self.climate_change.read()

    def write_attribute_files(self) -> None:
        """Writes all attribute files"""
        self.grid.write()

        self.wave_boundary_conditions.write()
        self.structures.write()
        self.initial_conditions.write()
        self.dunes.write()
        self.nourishments.write()
        self.tide.write()
        self.runup.write()
        self.climate_change.write()

    def clear_spatial_attributes(self) -> None:
        """Clear spatial data that can be regenerated by the toolbox."""
        self.grid = ShorelinesDomain(self)
        self.wave_boundary_conditions = ShorelinesWaveBoundaryConditions(self)
        self.structures = ShorelinesStructures(self)
        self.initial_conditions = ShorelinesInitialConditions(self)
        self.dunes = ShorelinesDunes(self)
        self.nourishments = ShorelinesNourishments(self)
        self.tide = ShorelinesTide(self)
        self.runup = ShorelinesRunup(self)
        self.climate_change = ShorelinesClimateChange(self)

    def write_matlab_runner(
        self,
        name: PathLike | None = None,
        shoreline_functions_path: PathLike | None = None,
    ) -> Path:
        """Write a MATLAB script that starts the generated ShorelineS case."""
        if shoreline_functions_path is None:
            shoreline_functions_path = self.function_path
        if name is None:
            name = f"run_{Path(self.input.runfile_name).stem}.m"
        else:
            name = normalize_optional_file_name(name, argument="name")
        path = Path(self.path) / name
        runfile = self.input.runfile_name.replace("\\", "/")
        functions_path = str(shoreline_functions_path).replace("'", "''")
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(
            "\n".join(
                [
                    f"addpath(genpath('{functions_path}'));",
                    f"runShorelineS('{runfile}');",
                    "",
                ]
            ),
            encoding="utf-8",
            newline="\n",
        )
        return path

    def check_times(self) -> tuple[bool, list[str]]:
        """
        Check whether forcing time series cover the simulation period.

        Returns
        -------
        tuple of bool and list of str
            Boolean success flag and validation messages for uncovered periods.
        """
        # Check that the boundary and other forcing fully covers the simulation time
        messages = []
        okay = True

        # Boundary conditions
        ok, message = self.wave_boundary_conditions.check_times()
        if not ok:
            okay = False
            messages.extend(message)

        ok, message = self.dunes.check_times()
        if not ok:
            okay = False
            messages.extend(message)

        return okay, messages
